apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourapp-deployment-1
  labels:
    app: yourapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yourapp
  template:
    metadata:
      labels:
        app: yourapp
    spec:
      containers:
      - name: yourapp-container-1
        image: tomcat:9.0-alpine
        ports:
        - containerPort: 8080
