apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourapp-deployment
  labels:
    app: yourapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yourapp
  template:
    metadata:
      labels:
        app: yourapp
    spec:
      containers:
      - name: yourapp-container
        image: vijaybabu09/vijayimage:latest
        ports:
        - containerPort: 80
